### ISSUE TITLE
笔记

### ISSUE THREAD

**Issue by bflhjn1220** [SsageParuders/CheatUnityGames#1]
最近国际服的老外出现了大量的sh执行文件
有可能使用的就是你这个思路

**Comment by SsageParuders** [comment]
sh执行文件我不清楚，我这个属于so注入&hook。
只不过偏向于Unity游戏了一点 ......
(后期有能力的话也会研究研究虚幻引擎的游戏)

---
是你啊，话说为啥还单独开个issues说话
QQ找我啊

**Comment by bflhjn1220** [comment]
。

**Comment by bflhjn1220** [comment]
QQ都删我屏蔽三连了你

**Comment by SsageParuders** [comment]
> 

？什么情况
我等会儿看一下

**Comment by bflhjn1220** [comment]
你不知道我吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月27日(星期天) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SsageParuders/CheatUnityGames] 笔记 (Issue #1)





   
？什么情况
 我等会儿看一下

**Comment by bflhjn1220** [comment]
你不理我，我无语了，然后我删好友了，你还不同意




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月27日(星期天) 晚上9:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SsageParuders/CheatUnityGames] 笔记 (Issue #1)





   
？什么情况
 我等会儿看一下

**Comment by bflhjn1220** [comment]
？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SsageParuders/CheatUnityGames"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月27日(星期天) 晚上9:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SsageParuders/CheatUnityGames] 笔记 (Issue #1)





   
？什么情况
 我等会儿看一下
